### ISSUE TITLE
小白请教大佬！！！

### ISSUE THREAD

**Issue by jinxiaokuang** [Actually123/Deep_Learning_Homeworks#1]
关于上机练习 8（LSTM生成古诗）：
        请问大佬为什么我的古诗生成效果不好呢？断断续续的并且有些关键字的故事没有生成是为啥呢？ @ShoutaoSun

**Comment by ShoutaoSun** [comment]
本实验采用的是最简单的RNN结构，对于文本信息的提取和生成能力有限，所生成古诗的效果并不尽如人意，望理解。本实验的主要目的是帮助学习者理解和应用简单的RNN结构，若想取得更好的效果，请查找最新最优秀的文本生成模型。

**Comment by jinxiaokuang** [comment]
好好好












金小矿
***@***.***






---原始邮件---
发件人: "Shoutao ***@***.***&gt;
发送时间: 2024年9月12日(周四) 下午3:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ShoutaoSun/Deep_Learning_Homeworks] 小白请教大佬！！！ (Issue #1)




 
Closed #1 as completed.
